
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port:
    password:
    timeout: 20000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
eureka:
  client:
    service-url:
      defaultZone: http://10.12.159.122:9090/eureka