server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://10.12.159.122:9090/eureka
spring:
  application:
    name: xp-produce-login
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bushome?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
mybatis:
  type-aliases-package: com.qf.j1902.pojo
  mapper-locations: classpath:mapping/*.xml